language: node_js
node_js:
  - "stable"
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable

services:
  - xvfb

before_script:
  - sleep 3 # give xvfb some time to start
  - npm install
  - npm run lint
